# EDA

## Preparing Data
- load multiple json files into dataframes
    - generate one dataframe per channel

## Assess and Clean Data
- drop columns which doesn't make sense
- drop rows which doesn't make sense
- clear text which is not needed
- change data types if needed
- get normal date from timestamp

## Wrangle Data
- create a couple of boolean columns from reactions, files, attachments, replies

In [1]:
# import basic libraries
import os, json
import pandas as pd
import numpy as np
import glob
pd.options.mode.chained_assignment = None

### Loading Multiple Json Files into DataFrames
Generate one dataframe with all the channels in it

In [2]:
main_folder_path = '../raw_data' 

def parse_all_json(main_folder_path):
    df = pd.DataFrame()

### Iterate through the group of folders
    for folder in os.listdir(main_folder_path):
        folder_path = os.path.join(main_folder_path, folder)
        
        if os.path.isdir(folder_path):
## Iterate through each individual folder
            for file in os.listdir(folder_path):
                file = os.path.join(main_folder_path, folder, file)
            
            #add a channel name column and add which folder is the value coming from: general, labhelp, 
                if file.endswith('.json'):
                    data = pd.read_json(file)
                    data['channel_name'] = folder
                    df = pd.concat([df, data])
    return df

#def get_text_content(df):
#return df['text']

#if __name__ == '__main__':
data = parse_all_json('../raw_data/')

In [3]:
# save to csv
data.to_csv(r'../csv/data_raw.csv', index = False)

### Assessment

In [4]:
data.shape

(5185, 38)

In [5]:
data.head()

,type,subtype,ts,user,text,channel_name,client_msg_id,team,user_team,source_team,...,bot_id,bot_profile,inviter,purpose,topic,root,old_name,name,x_files,hidden
0,message,channel_join,1.616237e+09,U01S1CWGTU4,<@U01S1CWGTU4> has joined the channel,music,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,message,NaN,1.617897e+09,U01S7BM4N81,<https://www.youtube.com/watch?v=qW1eTP9CKSE>,music,98d2a1df-fcab-4a15-a96c-514cd4fa55fa,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,message,NaN,1.620900e+09,U01RXCQHMHT,A thematic name for a playlist\n\n<https://sou...,music,c097123a-a43a-47a7-8d6b-c4ed6574b2c6,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,message,NaN,1.620200e+09,U01S7KCL3DF,<@U01RXCQHMHT> here’s a bangin track about Nig...,music,a153f00e-8a2f-4c0f-9f4f-ebcf678f250e,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,message,NaN,1.620211e+09,U01RSRE0N3D,For all of you LotR ravers\n<https://www.youtu...,music,41475476-99d9-41d5-beb7-727785d8cd49,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# assess column names
data.columns

Index(['type', 'subtype', 'ts', 'user', 'text', 'channel_name',
       'client_msg_id', 'team', 'user_team', 'source_team', 'user_profile',
       'attachments', 'blocks', 'edited', 'reactions', 'thread_ts',
       'reply_count', 'reply_users_count', 'latest_reply', 'reply_users',
       'replies', 'is_locked', 'subscribed', 'last_read', 'parent_user_id',
       'files', 'upload', 'display_as_bot', 'bot_id', 'bot_profile', 'inviter',
       'purpose', 'topic', 'root', 'old_name', 'name', 'x_files', 'hidden'],
      dtype='object')

In [7]:
# make a copy
df = data.copy()

In [8]:
# assess column names
df.columns

Index(['type', 'subtype', 'ts', 'user', 'text', 'channel_name',
       'client_msg_id', 'team', 'user_team', 'source_team', 'user_profile',
       'attachments', 'blocks', 'edited', 'reactions', 'thread_ts',
       'reply_count', 'reply_users_count', 'latest_reply', 'reply_users',
       'replies', 'is_locked', 'subscribed', 'last_read', 'parent_user_id',
       'files', 'upload', 'display_as_bot', 'bot_id', 'bot_profile', 'inviter',
       'purpose', 'topic', 'root', 'old_name', 'name', 'x_files', 'hidden'],
      dtype='object')

In [9]:
# check how many values each channel has
df.channel_name.value_counts()

lab-help                1777
general                 1342
random                   465
data-memes               302
data-viz-beauties        265
music                    227
data_resources           199
katas                    172
fun_committee            159
final-project            134
web-scraping-latino       37
vanilla_plus_more         33
project-storytelling      24
rogue-squadron            21
data-bootcamp             20
frustrations-shared        3
books                      3
rogue-one                  2
Name: channel_name, dtype: int64

In [10]:
# list of columns, their non-null objects and data type of columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5185 entries, 0 to 36
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   type               5185 non-null   object
 1   subtype            338 non-null    object
 2   ts                 5185 non-null   float64
 3   user               5184 non-null   object
 4   text               5185 non-null   object
 5   channel_name       5185 non-null   object
 6   client_msg_id      4279 non-null   object
 7   team               4323 non-null   object
 8   user_team          4227 non-null   object
 9   source_team        4227 non-null   object
 10  user_profile       4227 non-null   object
 11  attachments        424 non-null    object
 12  blocks             4668 non-null   object
 13  edited             315 non-null    object
 14  reactions          1096 non-null   object
 15  thread_ts          3974 non-null   float64
 16  reply_count        583 non-null    float64
 17  reply_users_count  583 non-null    float64
 18  latest_reply       583 non-null    float64
 19  reply_users        583 non-null    object
 20  replies            583 non-null    object
 21  is_locked          583 non-null    float64
 22  subscribed         583 non-null    float64
 23  last_read          89 non-null     float64
 24  parent_user_id     3369 non-null   object
 25  files              524 non-null    object
 26  upload             524 non-null    float64
 27  display_as_bot     503 non-null    float64
 28  bot_id             97 non-null     object
 29  bot_profile        96 non-null     object
 30  inviter            194 non-null    object
 31  purpose            9 non-null      object
 32  topic              9 non-null      object
 33  root               2 non-null      object
 34  old_name           2 non-null      object
 35  name               2 non-null      object
 36  x_files            2 non-null      object
 37  hidden             1 non-null      float64
dtypes: float64(11), object(27)
memory usage: 1.5+ MB

In [11]:
#check if there are any null values in the dataset 
df.isna().mean().round(4) *100

type                  0.00
subtype              93.48
ts                    0.00
user                  0.02
text                  0.00
channel_name          0.00
client_msg_id        17.47
team                 16.62
user_team            18.48
source_team          18.48
user_profile         18.48
attachments          91.82
blocks                9.97
edited               93.92
reactions            78.86
thread_ts            23.36
reply_count          88.76
reply_users_count    88.76
latest_reply         88.76
reply_users          88.76
replies              88.76
is_locked            88.76
subscribed           88.76
last_read            98.28
parent_user_id       35.02
files                89.89
upload               89.89
display_as_bot       90.30
bot_id               98.13
bot_profile          98.15
inviter              96.26
purpose              99.83
topic                99.83
root                 99.96
old_name             99.96
name                 99.96
x_files              99.96
hidden               99.98
dtype: float64

Due to the nature of the dataset, the missing values are not because of missing data, but because some posts didn't have replies, attachments, etc. The only important thing is that each value is coming from a user, and it is because I can see there are no missing values at the text or user columns. So I intend to keep everything as it is. I will dive deeper into rows that I don't need: channel join messages for example.

In [12]:
df['subtype'].value_counts()

channel_join         309
channel_topic          9
channel_purpose        9
channel_archive        3
channel_unarchive      2
channel_name           2
thread_broadcast       2
bot_message            1
tombstone              1
Name: subtype, dtype: int64

**Summary of Assesment**

**Columns to drop:**
    - type, team, user_team, source_team, latest_reply, last_read, bot_id, bot_profile, display_as_bot, topic, blocks, edited, is_locked, subscribed, upload, display_as_bot, root, purpose, thread_ts, parent_used_id

**Columns to clean & wrangle:**\
    - subtype: filter out it's values from df, remove the original column\
    - ts: changing it to datetime, remove miliseconds, get days of the week, months of the year, type of the day, parts of the day\
    - user_profile: extract real_name in new column, remove the original\
    - attachments: extract title, text, link in new columns\
    - files: extract url_private and who shared\
    - attachments: extract title, text, link in new columns\
    - reactions: extract user, count, name of the emoji\

In [13]:
df_clean = df.copy()

In [14]:
df_clean.head()

,type,subtype,ts,user,text,channel_name,client_msg_id,team,user_team,source_team,...,bot_id,bot_profile,inviter,purpose,topic,root,old_name,name,x_files,hidden
0,message,channel_join,1.616237e+09,U01S1CWGTU4,<@U01S1CWGTU4> has joined the channel,music,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,message,NaN,1.617897e+09,U01S7BM4N81,<https://www.youtube.com/watch?v=qW1eTP9CKSE>,music,98d2a1df-fcab-4a15-a96c-514cd4fa55fa,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,message,NaN,1.620900e+09,U01RXCQHMHT,A thematic name for a playlist\n\n<https://sou...,music,c097123a-a43a-47a7-8d6b-c4ed6574b2c6,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,message,NaN,1.620200e+09,U01S7KCL3DF,<@U01RXCQHMHT> here’s a bangin track about Nig...,music,a153f00e-8a2f-4c0f-9f4f-ebcf678f250e,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,message,NaN,1.620211e+09,U01RSRE0N3D,For all of you LotR ravers\n<https://www.youtu...,music,41475476-99d9-41d5-beb7-727785d8cd49,T01RBRV5F7H,T01RBRV5F7H,T01RBRV5F7H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_clean.columns

Index(['type', 'subtype', 'ts', 'user', 'text', 'channel_name',
       'client_msg_id', 'team', 'user_team', 'source_team', 'user_profile',
       'attachments', 'blocks', 'edited', 'reactions', 'thread_ts',
       'reply_count', 'reply_users_count', 'latest_reply', 'reply_users',
       'replies', 'is_locked', 'subscribed', 'last_read', 'parent_user_id',
       'files', 'upload', 'display_as_bot', 'bot_id', 'bot_profile', 'inviter',
       'purpose', 'topic', 'root', 'old_name', 'name', 'x_files', 'hidden'],
      dtype='object')

### Cleaning

In [16]:
def clean_dataframe(df_clean):
    """this function is applied to clean the dataframe
    """
    # drop columns not needed
    df_clean.drop(['type', 'client_msg_id', 'team', 'user_team',
             'source_team', 'blocks', 'upload', 'display_as_bot',
             'thread_ts', 'latest_reply', 'is_locked', 'subscribed',
             'parent_user_id', 'bot_id', 'bot_profile', 'last_read', 'edited',
             'purpose', 'inviter', 'topic', 'root', 'old_name', 'name', 'hidden',
             'x_files'], axis=1, inplace=True)
    
    # filter out for the rows which has subtype values
    df_clean = df_clean[(df_clean.subtype != 'channel_join') & 
                                (df_clean.subtype != 'channel_join') &
                                (df_clean.subtype != 'channel_purpose') &
                                (df_clean.subtype != 'thread_broadcast')]
    # drop subtype column with the values we don't need anymore
    df_clean.drop('subtype', axis=1, inplace=True) 
    
    return df_clean

### Wrangling

In [17]:
def datetime_wrangling(df_clean):
    
    """this function is applied to summarise wrangling steps with datetime
    """
    # convert ts to datetime from float
    df_clean['ts'] = pd.to_datetime(df_clean['ts'], unit='s').astype('datetime64[s]')
    
    # create a column for the days of the week using the ts column
    df_clean['day_name'] = df_clean['ts'].dt.day_name()
    df_clean['day_number'] = pd.DatetimeIndex(df_clean['ts']).day
    
    # create a column for the months of the year using the ts column
    df_clean['month'] = pd.DatetimeIndex(df_clean['ts']).month

    # convert values to date time and then month names
    df_clean['month'] = pd.to_datetime(df_clean['month'], format='%m').dt.month_name()
    
    # create a column for the type of the weekday using the ts column
    df_clean['day_type'] = df_clean.ts.dt.weekday.apply(
    lambda x: 'Weekday' if x < 5 else 'Weekend')
    
    # create a column for the hour of the day using the ts column
    df_clean['time']= df_clean['ts'].dt.strftime('%H')
    
    # create a column for the parts of the day
    df_clean['dayparts'] = (df_clean['ts'].dt.hour % 24 + 4) // 4
    df_clean['dayparts'].replace({1: 'Late Night',
                      2: 'Early Morning',
                      3: 'Morning',
                      4: 'Afternoon',
                      5: 'Evening',
                      6: 'Night'}, inplace=True)
    # drop ts column
    df_clean.drop('ts', axis=1, inplace=True) 

    
    return df_clean

In [20]:
def return_attachments(txt):
    """this function is applied to column attachments to extract links
    """
    try:
        dictionary = (txt)[0]
        if 'original_url' in dictionary:
            return dictionary.get('original_url', 'None')
    except:
        return 'None'
    
df_clean['attachments'] = df_clean['attachments'].apply(return_attachments)
#df_clean.to_csv(r'../csv/links.csv', columns = header, index = False)

In [22]:
def real_name(x):
    """this function is applied to column user_profile to extract real_name
    """
    if x != x:
        return 'noname'
    else:
        return x['real_name']

    
df_clean['real_name'] = df_clean['user_profile'].apply(real_name)

# drop user_profile column
df_clean.drop('user_profile', axis=1, inplace=True)

In [25]:
def reactions_count(txt):
    """this function is applied to column reactions to count reactions
    """
    try:
        dictionary = eval(txt)[0]
        if 'reactions' in dictionary:
            return dictionary.get('reactions', 'None')
    except:
        return 'None'
    
df_clean['reactions_count'] = df_clean['reactions'].apply(reactions_count)

In [26]:
def reactions_name(txt):
    """this function is applied to column reactions to count them
    """
    
    try:
        dictionary = eval(txt)[0]
        if 'name' in dictionary:
            return dictionary.get('name', 'None')
    except:
        return 'None'

df_clean['reactions_name'] = df_clean['reactions'].apply(reactions_name)

In [27]:
def boolean_features(df_clean):
    """this function is applied to create a new column with boolean features
    """
    
    # create a new boolean column if comment has reaction
    df_clean['reaction_true'] = df_clean['reactions_name'].isna()

    # create a new boolean column if comment has reply
    df_clean['replies_true'] = df_clean['reply_count'].isna()

    # create a new boolean column if comment has attachments
    df_clean['attachments_true'] = df_clean['attachments'].isna()
    
    return df_clean

In [28]:
def type_of_participant(s):
    """this function is applied to create a new column with teaching and students
    """
    if s == 'siand the LT (she/her)':
        return 'teacher'
    if s ==  'Florian Titze':
        return 'teacher'
    if s ==  'Kosta':
        return 'teacher'
    else:
        return 'student'
    return ''

# apply
df_clean['participant'] = df_clean['real_name'].apply(type_of_participant)

In [29]:
def text_length(df_clean):
    """this function is applied to create a new column with text length
    """
    df_clean['text_length'] = df_clean['text'].astype(str).map(len)
    
    return df_clean

In [30]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5185 entries, 0 to 36
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   type               5185 non-null   object
 1   subtype            338 non-null    object
 2   ts                 5185 non-null   float64
 3   user               5184 non-null   object
 4   text               5185 non-null   object
 5   channel_name       5185 non-null   object
 6   client_msg_id      4279 non-null   object
 7   team               4323 non-null   object
 8   user_team          4227 non-null   object
 9   source_team        4227 non-null   object
 10  attachments        5143 non-null   object
 11  blocks             4668 non-null   object
 12  edited             315 non-null    object
 13  reactions          1096 non-null   object
 14  thread_ts          3974 non-null   float64
 15  reply_count        583 non-null    float64
 16  reply_users_count  583 non-null    float64
 17  latest_reply       583 non-null    float64
 18  reply_users        583 non-null    object
 19  replies            583 non-null    object
 20  is_locked          583 non-null    float64
 21  subscribed         583 non-null    float64
 22  last_read          89 non-null     float64
 23  parent_user_id     3369 non-null   object
 24  files              524 non-null    object
 25  upload             524 non-null    float64
 26  display_as_bot     503 non-null    float64
 27  bot_id             97 non-null     object
 28  bot_profile        96 non-null     object
 29  inviter            194 non-null    object
 30  purpose            9 non-null      object
 31  topic              9 non-null      object
 32  root               2 non-null      object
 33  old_name           2 non-null      object
 34  name               2 non-null      object
 35  x_files            2 non-null      object
 36  hidden             1 non-null      float64
 37  real_name          5185 non-null   object
 38  reactions_count    5185 non-null   object
 39  reactions_name     5185 non-null   object
 40  participant        5185 non-null   object
dtypes: float64(11), object(30)
memory usage: 1.7+ MB

### Function calls

In [31]:
df_clean = clean_dataframe(df_clean)
df_clean = datetime_wrangling(df_clean)
df_clean = boolean_features(df_clean)
df_clean = text_length(df_clean)

### Cleaning again after Feature engineering

In [32]:
def clean_post_feature_eng(df_clean):
    
   # droppig unneccessary columns
    df_clean.drop(['reactions', 'reply_users', 'replies'], axis=1, inplace=True)
    
    # replace None values with zero
    df_clean['reply_count'] = df_clean['reply_count'].fillna(0)
    df_clean['reply_users_count'] = df_clean['reply_users_count'].fillna(0)
    df_clean['reply_count'] = df_clean['reply_count'].astype(int)
    df_clean['reply_users_count'] = df_clean['reply_users_count'].astype(int)
    
    # reordering columns
    df_clean = df_clean[['channel_name', 'user', 'real_name', 'participant',
                     'text', 'text_length', 'reply_count', 'reply_users_count',
                     'replies_true', 'day_name', 'day_type', 'time',
                     'dayparts', 'day_number', 'month', 'reactions_count', 
                     'reactions_name', 'attachments', 'attachments_true', 'reaction_true']]
    
    return df_clean

In [33]:
df_clean = clean_post_feature_eng(df_clean)

In [34]:
df_clean.head()

,channel_name,user,real_name,participant,text,text_length,reply_count,reply_users_count,replies_true,day_name,day_type,time,dayparts,day_number,month,reactions_count,reactions_name,attachments,attachments_true,reaction_true
0,music,U01S7BM4N81,Thamo,student,<https://www.youtube.com/watch?v=qW1eTP9CKSE>,45,0,0,True,Thursday,Weekday,15,Afternoon,8,April,None,None,https://www.youtube.com/watch?v=qW1eTP9CKSE,False,False
0,music,U01RXCQHMHT,Thanh Tung Ha Thuc DAFT Berlin March 2021,student,A thematic name for a playlist\n\n<https://sou...,82,0,0,True,Thursday,Weekday,09,Morning,13,May,None,None,https://soundcloud.com/ryan-celsius/study-or-die,False,False
0,music,U01S7KCL3DF,Sam Katterfield,student,<@U01RXCQHMHT> here’s a bangin track about Nig...,142,0,0,True,Wednesday,Weekday,07,Early Morning,5,May,None,None,https://open.spotify.com/track/4IPZISKACJIbVKV...,False,False
1,music,U01RSRE0N3D,Kosta,teacher,For all of you LotR ravers\n<https://www.youtu...,72,2,2,False,Wednesday,Weekday,10,Morning,5,May,None,None,https://www.youtube.com/watch?v=z9Uz1icjwrM,False,False
2,music,U01RW2X7S9Z,Alexandre Sommerkamp,student,"my recommender:\n`input(""introduce your song:""...",104,0,0,True,Wednesday,Weekday,11,Morning,5,May,None,None,None,False,False

In [36]:
# save to csv
df_clean.to_csv(r'../csv/data_clean_optimized.csv', index = False)

In [37]:
# save to excel
df_clean.to_excel(r'../csv/data_clean_optimized.xlsx', index = False)